### ISSUE TITLE
Design draft for allowing online editing of documentation.

### ISSUE THREAD

**Issue by MathieuDuponchelle** [MathieuDuponchelle/hotdoc#33]
## Targets

The target here isn't the developer actually involved in a given project, but rather:

* The casual user that just wants to make a drive-by patch, and can't be bothered to 
set up everything locally

* The non-tech-savvy user that for example wants to contribute a quick guide for
a given feature of a project, not necessarily a library, rather an application.

## Requirements

* "Instant gratification" -> live previewing, a posteriori review.
* Ability to edit anything, from standalone markdown pages to python code snippets.
* Avoid spam as much as possible.

### Previewing

The initial implementation will rely on hotdoc as a server. The preview will be periodically refreshed
by making calls to the server and rerendering the html result (probably in an iframe).

In a second time, we can refine this incrementally by implementing (javascript) client-side renderers for the various formats, probably starting with the standalone markdown pages.

### Instant gratification

The system will maintain a staging git branch, with its HEAD initially pointing to master. Each edit
will be commited separately, including the possibility of a "revert to master", which will actually
be commited as a revert, preserving potentially good edits.

The reviewer will then be able to easily review these commits and pull them to master if appropriate,
then reset the system to its initial state (staging branch pointing to master).

### Spam prevention

We hope that authentication through openID / a github account will be a low enough barrier for potential
contributors, and a high enough one for spammers. That's just a wish though, and spam control is more
important here than on blog comments for example, as editors can potentially deface an entire
documentation. There should thus be the possibility for the maintainer to switch to an a priori review.

## Subtasks

- [x] Design and implement an online API for hotdoc (#38)
- [x] Reimplement incremental building of the documentation, as this will be paramount to the smoothness of the previewing process (#36)
- [x] Design and implement a web frontend, looking at [dillinger](http://www.dillinger.io) and other online editing
projects for inspiration and potential code reusability (#39)

**Comment by MathieuDuponchelle** [comment]
The upstream for this is now https://github.com/MathieuDuponchelle/hotdoc_server
